---
version: 2
triggers: [ ]

plan:
  project-key: CL
  key: VLEBD
  name: VpnLibsEndpoint - Deploy

stages:
  - Build artifacts:
      manual: false
      final: false
      jobs:
        - Build on Linux
        - Build on macOS
  - Deploy artifacts:
      manual: false
      final: false
      jobs:
        - Deploy artifacts

Build on Linux:
  key: BL
  docker:
    image: adguard/core-libs:1.11
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
      ${bamboo.git.cache.directory}: ${bamboo.git.cache.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -x -e
            cargo build --release --target x86_64-unknown-linux-gnu
            cp target/x86_64-unknown-linux-gnu/release/vpn_endpoint target/vpn_endpoint.linux-x86_64
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]
  artifacts:
    - name: Build result Linux
      location: target
      pattern: 'vpn_endpoint.linux-x86_64'
      required: false
      shared: true

Build on macOS:
  key: BM
  tasks:
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -x -e
            cargo build --release --target x86_64-apple-darwin
            cp target/x86_64-apple-darwin/release/vpn_endpoint target/vpn_endpoint.osx-x86_64
  requirements:
    - macOS 11.0 or later
  artifact-subscriptions: [ ]
  artifacts:
    - name: Build result macOS
      location: target
      pattern: 'vpn_endpoint.osx-x86_64'
      required: false
      shared: true

Deploy artifacts:
  key: DA
  docker:
    image: adguard/core-libs:1.11
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
      ${bamboo.git.cache.directory}: ${bamboo.git.cache.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: [ ]
  tasks:
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            
            set -x -e
            VERSION=$(cat Cargo.toml | grep "version = " | head -n 1 | sed -e 's/version = "\(.*\)"/\1/')
            ART_URL=${bamboo.artifactoryAdguardMavenUrl}
            ART_VER=${VERSION}
            
            # Build
            pushd vpn-endpoint-build-results
            zip ../vpn_endpoint-$VERSION.zip *
            popd
            
            # Tag release or change URL to snapshots
            case "${bamboo_repository_branch_name}" in
            master|stable-*)
              git remote set-url origin ${bamboo_planRepository_repositoryUrl}
              git reset
              git tag v$VERSION || true
              git push origin v$VERSION
              ;;
            *)
              ART_VER="${ART_VER}-snapshot"
              ART_URL=${bamboo.artifactoryAdguardMavenSnapshotsUrl}
              ;;
            esac
            
            # Deploy to Maven
            cat > settings.xml <<EOF
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                    https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                <server>
                  <id>Artifactory</id>
                    <username>${bamboo.artifactoryUser}</username>
                    <password>${bamboo.artifactoryPassword}</password>
                </server>
              </servers>
            </settings>
            EOF
            mvn --settings settings.xml deploy:deploy-file \
              -DgroupId=com.adguard.corelibs \
              -DartifactId=vpn-libs-endpoint \
              -Dversion=$ART_VER \
              -Dpackaging=zip \
              -Dfile=vpn_endpoint-${VERSION}.zip \
              -DrepositoryId=Artifactory \
              -Durl=$ART_URL
            rm settings.xml
  requirements:
    - adg-privileged-docker
  artifact-subscriptions:
    - artifact: Build result Linux
      destination: vpn-endpoint-build-results
    - artifact: Build result macOS
      destination: vpn-endpoint-build-results
  artifacts:
    - name: Distribution
      location: .
      pattern: 'vpn_endpoint-*.zip'
      required: false

repositories:
  - core-libs/vpn-libs-endpoint:
      scope: global

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications: [ ]

labels: [ ]

other:
  concurrent-build-plugin: system-default
